### ISSUE TITLE
line break after synonyms in IPCC and Crustal Scarcity

### ISSUE THREAD

**Issue by conradspindler** [ecoinvent/lcia#1]
There is a small issue that the mapping files for "Crustal Scarcity Indicator 2020" and "IPCC 2021" have a line break after each synonym instead of a semicolon which is not the case in the other mapping files (each exchange in one line, synonyms separated by semicolon). This makes it difficult to load in the "Crustal Scarcity Indicator 2020" and "IPCC 2021".

**Comment by thomassonderegger** [comment]
Thanks a lot for checking, the issue is solved.
